run:
  timeout: 5m
  modules-download-mode: readonly

# output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # Default: colored-line-number
  format: colored-line-number
  # Print lines of code with issue.
  # Default: true
  print-issued-lines: true
  # Print linter name in the end of issue text.
  # Default: true
  print-linter-name: true
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false
  # Sort results by: filepath, line and column.
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
#    - golint
    - govet
#    - staticcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 200
  max-same-issues: 0